# Generated by Django 4.0.3 on 2022-10-31 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import remit_api.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoces',
            fields=[
                ('invoices_commit', models.DateTimeField(default=django.utils.timezone.now)),
                ('invoive_id', models.CharField(default=uuid.uuid4, editable=False, max_length=150, primary_key=True, serialize=False)),
                ('receiver_phone', models.IntegerField(blank=True, null=True)),
                ('agent', models.ForeignKey(default=remit_api.models.get_default_agent, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invoices Detail',
                'verbose_name_plural': 'Invoce Records',
            },
        ),
        migrations.CreateModel(
            name='Operators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(blank=True, max_length=50, null=True)),
                ('operator_order', models.IntegerField(blank=True, null=True)),
                ('operator_discount_rate', models.FloatField(blank=True, null=True)),
                ('operator_image_link', models.TextField(blank=True, null=True)),
                ('operator_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Network Operator Info',
                'verbose_name_plural': 'Mobile Network Operators',
            },
        ),
        migrations.CreateModel(
            name='PackageOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_order', models.IntegerField(blank=True, null=True)),
                ('airtime_value', models.FloatField(blank=True, null=True)),
                ('selling_price_ETB', models.FloatField(blank=True, null=True)),
                ('forex_rate', models.FloatField(blank=True, null=True)),
                ('selling_price_USD', models.FloatField(blank=True, null=True)),
                ('discount_rate', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Package Offer Detail',
                'verbose_name_plural': 'Package Offers',
                'ordering': ('package_order',),
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(blank=True, max_length=50, null=True)),
                ('provider_order', models.IntegerField(blank=True, null=True)),
                ('provider_image_link', models.TextField(blank=True, null=True)),
                ('provider_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Payment Provider',
                'verbose_name_plural': 'Payment Providers list',
            },
        ),
        migrations.CreateModel(
            name='PromoCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promoter', models.CharField(blank=True, max_length=150, null=True)),
                ('promo_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('promo_discount_rate', models.FloatField(blank=True, null=True)),
                ('promo_expiry_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Promotion Discount Detail',
                'verbose_name_plural': 'Promotion Discount Listings',
                'ordering': ('promoter',),
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.CharField(default=uuid.uuid4, editable=False, max_length=150, primary_key=True, serialize=False)),
                ('committed_on', models.DateTimeField(blank=True, null=True)),
                ('transaction_status', models.CharField(default='COMMITTED', max_length=50)),
                ('transaction_amount_USD', models.FloatField(blank=True, null=True)),
                ('airtime_amount', models.FloatField(blank=True, null=True)),
                ('sells_amount_ETB', models.FloatField(blank=True, null=True)),
                ('agent_name', models.CharField(blank=True, max_length=50, null=True)),
                ('commision', models.FloatField(blank=True, null=True)),
                ('payment_owed', models.FloatField(blank=True, null=True)),
                ('is_commission_paid', models.BooleanField(default=False)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='remit_api.invoces')),
            ],
            options={
                'verbose_name': 'Transactions Detail',
                'verbose_name_plural': 'Transactions Records',
            },
        ),
        migrations.AddField(
            model_name='invoces',
            name='operator',
            field=models.ForeignKey(default=remit_api.models.get_default_operator, on_delete=django.db.models.deletion.SET_DEFAULT, to='remit_api.operators'),
        ),
        migrations.AddField(
            model_name='invoces',
            name='package_offers',
            field=models.ForeignKey(default=remit_api.models.get_default_package, on_delete=models.SET(remit_api.models.get_default_package), to='remit_api.packageoffers'),
        ),
        migrations.AddField(
            model_name='invoces',
            name='payment_method',
            field=models.ForeignKey(default=remit_api.models.get_default_payment, on_delete=django.db.models.deletion.SET_DEFAULT, to='remit_api.paymentmethod'),
        ),
        migrations.AddField(
            model_name='invoces',
            name='promo_code',
            field=models.ForeignKey(default=remit_api.models.get_default_promo, on_delete=django.db.models.deletion.SET_DEFAULT, to='remit_api.promocodes'),
        ),
    ]
