# Generated by Django 4.0.3 on 2022-10-17 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remit_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packageoffers',
            options={'ordering': ('package_order',), 'verbose_name': 'Package Offer Detail', 'verbose_name_plural': 'Package Offers'},
        ),
        migrations.AlterModelOptions(
            name='promocodes',
            options={'ordering': ('promoter',), 'verbose_name': 'Promotion Discount Detail', 'verbose_name_plural': 'Promotion Discount Listings'},
        ),
    ]
