# Generated by Django 4.0.3 on 2022-10-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remit_api', '0002_alter_packageoffers_options_alter_promocodes_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocodes',
            name='promo_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
