# Generated by Django 4.0.3 on 2022-10-03 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_helpers.upload_to_helpers
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('agent_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=model_helpers.upload_to_helpers.upload_to),
        ),
        migrations.CreateModel(
            name='PaymentsTracker',
            fields=[
                ('payment_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_id', models.CharField(default=uuid.uuid4, editable=False, max_length=150, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(blank=True, max_length=150, null=True)),
                ('payment_bank', models.CharField(blank=True, max_length=150, null=True)),
                ('transaction_number', models.CharField(blank=True, max_length=150, null=True)),
                ('paid_amount', models.FloatField(blank=True, null=True)),
                ('total_sell', models.FloatField(blank=True, null=True)),
                ('commision', models.FloatField(blank=True, null=True)),
                ('total_payment', models.FloatField(blank=True, null=True)),
                ('remaining_payment', models.FloatField(blank=True, null=True)),
                ('payment_for', models.ForeignKey(default={'Cause': 'Payment Unavailable', 'agent_name': 'DEFAULT', 'id': 'None'}, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
