# Generated by Django 4.0.3 on 2022-10-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentstracker',
            options={'ordering': ('-payment_time',)},
        ),
        migrations.AddField(
            model_name='notifications',
            name='task',
            field=models.CharField(blank=True, max_length=144, null=True),
        ),
    ]
