# Generated by Django 4.0.3 on 2022-10-03 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent_api', '0002_alter_agentprofile_image_paymentstracker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentstracker',
            old_name='payment_for',
            new_name='agent_name',
        ),
    ]
