# Generated by Django 4.0.3 on 2022-10-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_api', '0002_alter_paymentstracker_options_notifications_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='is_viewed',
        ),
        migrations.AddField(
            model_name='notifications',
            name='is_unread',
            field=models.BooleanField(default=True),
        ),
    ]
