# Generated by Django 4.0.3 on 2022-10-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_api', '0003_remove_notifications_is_viewed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsupdate',
            options={'ordering': ('-update_time',)},
        ),
        migrations.AlterModelOptions(
            name='notifications',
            options={'ordering': ('-notification_time',)},
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notice',
            field=models.TextField(blank=True, null=True),
        ),
    ]
