# Generated by Django 4.0.3 on 2022-10-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_api', '0004_alter_newsupdate_options_alter_notifications_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentstracker',
            name='total_agent_payment',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
